### ISSUE TITLE
ModuleNotFoundError: No module named 'anthropic.api'.

### ISSUE THREAD

**Issue by vipulchaube** [kagisearch/pyllms#11]
I am encountringi this error ModuleNotFoundError: No module named 'anthropic.api'.  I just installed it and tried checking out the model list 

import llms

model = llms.init()
model.list()

**Comment by z64** [comment]
Hi @vipulchaube ,

Currently there is an incompatibility with `anthropic` >=0.3, and we haven't updated pyllms yet to work with it - we will do so ASAP (a pull request would also be welcome)

If you can, you can downgrade to `antrophic` v0.2.10 for example - the last version before 0.3 - it should work OK.

**Comment by vipulchaube** [comment]
Thanks.
It works on downgrading anthropic

**Comment by bkiat1123** [comment]
Anthropic 0.3 is supported in the latest pyllms release of 0.3.
